### ISSUE TITLE
League Checklist

### ISSUE THREAD

**Issue by philsturgeon** [zackkitzmiller/tiny-php#9]
You asked me to do this, so I'm doing it!

- [ ] Update README.md to be more like [Skeleton](https://github.com/thephpleague/skeleton/blob/master/README.md)
- [ ] Switch to `League\` namespace
- [x] Add [coveralls](https://coveralls.io/)
- [x] Add a LICENSE.md for MIT
- [ ] PSR-2 compliance
- [ ] PSR-4 compliance
- [ ] Improve intro, to explain to any muppet what this is and exactly why they want to use it

**Comment by kylestev** [comment]
Is there still an interest in migrating this to the League? I'd love to help!

**Comment by zackkitzmiller** [comment]
@kylestev Absolutely. I'm happy to have anyone make the necessary changes. I'm just swamped w/ SeatGeek stuff.

**Comment by kylestev** [comment]
I'll start putting together a PR then. Cheers!

**Comment by zackkitzmiller** [comment]
Awesome! Thanks you, @kylestev

**Comment by kylestev** [comment]
@zackkitzmiller waiting on the tests now :smile: let me know if anything looks off, needs to be added, etc.!

**Comment by jwpage** [comment]
Oh yeah, I said I'd do this. Looks like I dropped the ball on that one,
sorry!
